#!/bin/csh
set Ea0=-15296.570
set Eb0=-15296.432
set tolE0=0.01
# set tolerance in cm-1

set Ea=`grep "STATE   1: REL" $1 | awk '{ print $5 }'`0
set Eb=`grep "STATE   2: REL" $1 | awk '{ print $5 }'`0
set ierr=0
set Eaerr=`$chkabs $Ea $Ea0 $tolE0`
if($status != 0) set ierr=1 
set Eberr=`$chkabs $Eb $Eb0 $tolE0`
if($status != 0) set ierr=1 
echo -n "Eerr=$Eaerr+$Eberr. "
exit $ierr 
