$ SET NOVERIFY
$!
$!    7 Dec 1993 - MWS
$!   Compile and link GAMESS' graphics under VMS operating system.
$!   Usage: $ SUBMIT COMPLINK (recommended) -or- $ @COMPLINK
$!   You need to have a C compiler, in addition to the usual FORTRAN.
$!
$!   The installer should customize the next lines, depending on
$!   whether X-windows screens or PostScript printers are available.
$!   Select arch from ALPHA, VAXSCALAR, VAXVECTOR
$!
$ xwindows = "TRUE"
$ postscript = "TRUE"
$ arch = "ALPHA"
$!
$ SET DEFAULT PLT:
$ SAY := WRITE SYS$OUTPUT
$!
$ IF arch.EQS."ALPHA"     THEN float="FLOAT=IEEE_FLOAT"
$ IF arch.EQS."VAXSCALAR" THEN float="NOG_FLOATING"
$ IF arch.EQS."VAXVECTOR" THEN float="NOG_FLOATING"
$ IF arch.EQS."ALPHA"     THEN clib="VAXCRTLT"
$ IF arch.EQS."VAXSCALAR" THEN clib="VAXCRTL"
$ IF arch.EQS."VAXVECTOR" THEN clib="VAXCRTL"
$!
$!   First activate all "*VMS" statements to produce SCR:XXX.TMP files
$!
$ SAY "Activating VMS dependent code..."
$ COPY DENDIF.CODE SCR:DENDIF.TMP
$ COPY MEPMAP.CODE SCR:MEPMAP.TMP
$ COPY PLTORB.CODE SCR:PLTORB.TMP
$ COPY KONTRS.CODE SCR:KONTRS.TMP
$!
$ ASSIGN/USER_MODE MOLPLT.CODE       SRCIN
$ ASSIGN/USER_MODE SCR:MOLPLT.TMP    CODEOUT
$ ASSIGN/USER_MODE SYS$INPUT         ACTIN
$ ASSIGN/USER_MODE SYS$OUTPUT        ACTOUT
$ RUN GAMESS:ACTVTE
*VMS
$ ASSIGN/USER_MODE UTILS.CODE        SRCIN
$ ASSIGN/USER_MODE SCR:UTILS.TMP     CODEOUT
$ ASSIGN/USER_MODE SYS$INPUT         ACTIN
$ ASSIGN/USER_MODE SYS$OUTPUT        ACTOUT
$ RUN GAMESS:ACTVTE
*VMS
$!
$!   ----- COMPILE AND LINK X-WINDOWS GRAPHICS -----
$!
$ IF xwindows.NES."TRUE" THEN GOTO END_OF_XW
$ IF F$MODE().EQS."BATCH" THEN SET PROCESS/NAME=CL_XW
$!
$ SAY "Activating X-windows related code..."
$ COPY SCR:UTILS.TMP  SCR:UTILS.FOR
$ COPY SCR:KONTRS.TMP SCR:KONTRS.FOR
$!
$ ASSIGN/USER_MODE SCR:DENDIF.TMP    SRCIN
$ ASSIGN/USER_MODE SCR:DENDIF.FOR    CODEOUT
$ ASSIGN/USER_MODE SYS$INPUT         ACTIN
$ ASSIGN/USER_MODE SYS$OUTPUT        ACTOUT
$ RUN GAMESS:ACTVTE
*XW
$ ASSIGN/USER_MODE SCR:MEPMAP.TMP    SRCIN
$ ASSIGN/USER_MODE SCR:MEPMAP.FOR    CODEOUT
$ ASSIGN/USER_MODE SYS$INPUT         ACTIN
$ ASSIGN/USER_MODE SYS$OUTPUT        ACTOUT
$ RUN GAMESS:ACTVTE
*XW
$ ASSIGN/USER_MODE SCR:MOLPLT.TMP    SRCIN
$ ASSIGN/USER_MODE SCR:MOLPLT.FOR    CODEOUT
$ ASSIGN/USER_MODE SYS$INPUT         ACTIN
$ ASSIGN/USER_MODE SYS$OUTPUT        ACTOUT
$ RUN GAMESS:ACTVTE
*XW
$ ASSIGN/USER_MODE SCR:PLTORB.TMP    SRCIN
$ ASSIGN/USER_MODE SCR:PLTORB.FOR    CODEOUT
$ ASSIGN/USER_MODE SYS$INPUT         ACTIN
$ ASSIGN/USER_MODE SYS$OUTPUT        ACTOUT
$ RUN GAMESS:ACTVTE
*XW
$!
$ SET VERIFY
$ FORTRAN/NOLIST/'float' SCR:DENDIF.FOR
$ FORTRAN/NOLIST/'float' SCR:MOLPLT.FOR
$ FORTRAN/NOLIST/'float' SCR:MEPMAP.FOR
$ FORTRAN/NOLIST/'float' SCR:PLTORB.FOR
$ FORTRAN/NOLIST/'float' SCR:UTILS.FOR
$ FORTRAN/NOLIST/'float' SCR:KONTRS.FOR
$ CC/NOLIST/'float' /DEFINE=(VMS,CAPS,ANSI) XWINDOWS.C /WARN=NOINFORMATIONAL
$!
$ LINK DENDIF,UTILS,KONTRS,XWINDOWS, -
     GAMESS:GAMESS.OLB/LIBRARY,SYS$SHARE:'clib'.OLB/LIBRARY,SYS$INPUT/OPTIONS -
     /EXECUTABLE=DENDIF_XW.EXE /NOMAP /TRACEBACK
SYS$SHARE:DECW$XLIBSHR.EXE/SHARE
$!
$ LINK MEPMAP,UTILS,KONTRS,XWINDOWS, -
     GAMESS:GAMESS.OLB/LIBRARY,SYS$SHARE:'clib'.OLB/LIBRARY,SYS$INPUT/OPTIONS -
     /EXECUTABLE=MEPMAP_XW.EXE /NOMAP /TRACEBACK
SYS$SHARE:DECW$XLIBSHR.EXE/SHARE
$!
$ LINK MOLPLT,UTILS,XWINDOWS, -
     GAMESS:GAMESS.OLB/LIBRARY,SYS$SHARE:'clib'.OLB/LIBRARY,SYS$INPUT/OPTIONS -
     /EXECUTABLE=MOLPLT_XW.EXE /NOMAP /TRACEBACK
SYS$SHARE:'clib'.OLB/LIB
SYS$SHARE:DECW$XLIBSHR.EXE/SHARE
$!
$ LINK PLTORB,UTILS,KONTRS,XWINDOWS, -
     GAMESS:GAMESS.OLB/LIBRARY,SYS$SHARE:'clib'.OLB/LIBRARY,SYS$INPUT/OPTIONS -
     /EXECUTABLE=PLTORB_XW.EXE /NOMAP /TRACEBACK
SYS$SHARE:DECW$XLIBSHR.EXE/SHARE
$ DELETE SCR:*.FOR;*
$ DELETE *.OBJ;*
$ SET NOVERIFY
$!
$ END_OF_XW:
$!
$!   ----- COMPILE AND LINK POSTSCRIPT GRAPHICS -----
$!
$ IF postscript.NES."TRUE" THEN GOTO END_OF_PS
$ IF F$MODE().EQS."BATCH" THEN SET PROCESS/NAME=CL_PS
$!
$ SAY "Activating PostScript related code..."
$ COPY SCR:UTILS.TMP  SCR:UTILS.FOR
$ COPY SCR:KONTRS.TMP SCR:KONTRS.FOR
$!
$ ASSIGN/USER_MODE SCR:DENDIF.TMP    SRCIN
$ ASSIGN/USER_MODE SCR:DENDIF.FOR    CODEOUT
$ ASSIGN/USER_MODE SYS$INPUT         ACTIN
$ ASSIGN/USER_MODE SYS$OUTPUT        ACTOUT
$ RUN GAMESS:ACTVTE
*PS
$ ASSIGN/USER_MODE SCR:MEPMAP.TMP    SRCIN
$ ASSIGN/USER_MODE SCR:MEPMAP.FOR    CODEOUT
$ ASSIGN/USER_MODE SYS$INPUT         ACTIN
$ ASSIGN/USER_MODE SYS$OUTPUT        ACTOUT
$ RUN GAMESS:ACTVTE
*PS
$ ASSIGN/USER_MODE SCR:MOLPLT.TMP    SRCIN
$ ASSIGN/USER_MODE SCR:MOLPLT.FOR    CODEOUT
$ ASSIGN/USER_MODE SYS$INPUT         ACTIN
$ ASSIGN/USER_MODE SYS$OUTPUT        ACTOUT
$ RUN GAMESS:ACTVTE
*PS
$ ASSIGN/USER_MODE SCR:PLTORB.TMP    SRCIN
$ ASSIGN/USER_MODE SCR:PLTORB.FOR    CODEOUT
$ ASSIGN/USER_MODE SYS$INPUT         ACTIN
$ ASSIGN/USER_MODE SYS$OUTPUT        ACTOUT
$ RUN GAMESS:ACTVTE
*PS
$!
$ SET VERIFY
$ FORTRAN/NOLIST/'float' SCR:DENDIF.FOR
$ FORTRAN/NOLIST/'float' SCR:MOLPLT.FOR
$ FORTRAN/NOLIST/'float' SCR:MEPMAP.FOR
$ FORTRAN/NOLIST/'float' SCR:PLTORB.FOR
$ FORTRAN/NOLIST/'float' SCR:UTILS.FOR
$ FORTRAN/NOLIST/'float' SCR:KONTRS.FOR
$ CC/NOLIST/'float' /DEFINE=(CAPS,ANSI) POSTSCR.C  /WARN=NOINFORMATIONAL
$!
$ LINK DENDIF,UTILS,KONTRS,POSTSCR, -
       GAMESS:GAMESS.OLB/LIBRARY,SYS$SHARE:'clib'.OLB/LIBRARY -
       /EXECUTABLE=DENDIF_PS.EXE /NOMAP /TRACEBACK
$!
$ LINK MEPMAP,UTILS,KONTRS,POSTSCR, -
       GAMESS:GAMESS.OLB/LIBRARY,SYS$SHARE:'clib'.OLB/LIBRARY -
       /EXECUTABLE=MEPMAP_PS.EXE /NOMAP /TRACEBACK
$!
$ LINK MOLPLT,UTILS,POSTSCR, -
       GAMESS:GAMESS.OLB/LIBRARY,SYS$SHARE:'clib'.OLB/LIBRARY -
       /EXECUTABLE=MOLPLT_PS.EXE /NOMAP /TRACEBACK
$!
$ LINK PLTORB,UTILS,KONTRS,POSTSCR, -
       GAMESS:GAMESS.OLB/LIBRARY,SYS$SHARE:'clib'.OLB/LIBRARY -
       /EXECUTABLE=PLTORB_PS.EXE /NOMAP /TRACEBACK
$!
$ DELETE SCR:*.FOR;*
$ DELETE *.OBJ;*
$ SET NOVERIFY
$!
$ END_OF_PS:
$!
$ DELETE SCR:*.TMP;*
$ EXIT
